id: https://linkml.org/linkml_config_model
title: Model for the LinkML model template configuration
name: config_model
license: https://creativecommons.org/publicdomain/zero/1.0/
version: 0.0.1

prefixes:
 linkml: https://w3id.org/linkml/
 conf: https://linkml.org/linkml_config/

default_prefix: conf
default_range: string

default_curi_maps:
  - semweb_context


types:
  string:
    uri: xsd:string
    base: str
    description: A character string

  boolean:
    uri: xsd:boolean
    base: Bool
    repr: bool
    description: A binary (true or false) value


classes:
  Config:
    description: Configuration parameters for linkml model template

    attributes:
      root_schema:
        description: The name of the root schema file (sans ".yaml")
        required: true

      model_name:
        description: The repository name of the model
        comments: Typically in the form of {topic}-model
        identifier: true

      model_py_name:
        description: The Python equivalent of the model name
        comments: If omitted, default to the model_name with '-' replaced by '_'

      model_organization:
        description: The github repository organization
        required: true

      model_author:
        description: The primary author of the model
        required: true

      model_author_email:
        description: The email address of the model author
        required: true

      model_synopsis:
        description: A short description of the model
        required: true

      model_description:
        description: A more detailed description of the model
        notes: Same as model synopsis

      model_url:
        description: URL of model documentation
        see_also: https://pypi.org/classifiers/
        comments: If omitted, defaults to "https://github.com/{model_organization}/{model_name}"

      classifiers:
        description: Trove classifiers for PyPI
        multivalued: true

      keywords:
        description: A list of keywords for PyPI
        multivalued: true

      generate:
        description: The set of components to generate
        range: component
        required: true
        multivalued: true

enums:
  component:
    description: LinkML Component to generate
    permissible_values:
      graphql:
        description: Emit model schema in GraphQL
      json:
        description: Emit model schema in JSON
      jsonld_context:
        description: Emit JSON-LD contexts for model instance to RDF transformations
      json_schema:
        description: Emit JSON Schema rendering of the model
      owl:
        description: Emit OWL representation of model schema
      rdf:
        description: Emit RDF representation of model schema
      shex:
        description: Emit ShEx representation of model schema
      sqlddl:
        description: Emit SQL Data Definition Language (create table statements) 
